name: bujuan
description: A clean MusicPlayer.
version: 2.0.4+25
environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  get: ^4.6.5
  # 依赖注入
  get_it: ^7.6.0
  # 路由管理
  auto_route: ^5.0.4

  # 加密库
  encrypt: ^5.0.1
  pointycastle: ^3.7.3

  # 本地存储
  path_provider: ^2.0.15
  hive_flutter: ^1.1.0

  #网络库
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  dio_cookie_manager: ^3.1.0
  cached_network_image: ^3.3.0

  # 音视频
  just_audio: ^0.9.36               # 音频播放
  audio_service: ^0.18.12           # 后台播放
  audio_video_progress_bar: ^1.0.1  # 播放进度条

  # 工具库
  date_format: ^2.0.7
  json_annotation: ^4.8.0
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  qr_flutter: ^4.1.0

  # 图片查看
  extended_image: ^8.2.0
  # 图片主色调提取
  palette_generator: ^0.3.3+3
  # 图片选择
  image_picker: ^0.8.9

  # 动画
  rive: ^0.11.3
  lottie: ^2.4.0

  # 屏幕适配
  flutter_screenutil: ^5.9.0
  # tabler图标库
  flutter_tabler_icons: ^1.1.2
  # 加载矢量图
  flutter_svg: ^2.0.7
  # 显示原生toast
  fluttertoast: ^8.2.2
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # 通知权限
  notification_permissions: ^0.6.1
  # 跨平台Dialog
  adaptive_dialog: ^1.9.0-0
  # 滑动倒计时组件
  slide_countdown: ^0.6.0
  # 权限请求组件
  permission_handler: ^10.2.0
  # UI 抽屉侧边栏
  flutter_zoom_drawer: ^3.1.1

  # 平台相关
  # 桌面平台窗口管理（大小、位置）
  window_manager: ^0.3.4
  # 安卓原生Intent
  android_intent_plus: ^4.0.1
  # 设置Android屏幕刷新率模式
  flutter_displaymode: ^0.6.0
  # 磨砂容器
  blurrycontainer: ^2.1.0
  # 约束布局
  flutter_constraintlayout: ^1.7.0-stable
  # 震动
  vibration: ^3.1.3
  flutter_lyric: ^2.0.4+6
  scrollable_positioned_list: ^0.3.8

#  flutter_rust_bridge: ^1.77.1
#  ffi: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  自动刷新路由表
  #  flutter packages pub run build_runner watch
  #  生成路由代码
  #  flutter packages pub run build_runner build
  auto_route_generator: 5.0.3
  build_runner:
  flutter_lints: ^2.0.0
  ffigen: ^8.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
